### ISSUE TITLE
The folder Outlook is missing from the repository

### ISSUE THREAD

**Issue by sudeepghatak** [asposeemail/Aspose_Email_NET#1]
Hi,  I am not able to build the project. The Folder "Outlook" in the solution is empty

![capture](https://cloud.githubusercontent.com/assets/12538280/9100127/31ede192-3c2b-11e5-9dae-be7345000374.PNG)

**Comment by saqib-razzaq-aspose** [comment]
Please pull/download again, it is included now and the project should build.
There was a rule in .gitignore file, which was keeping the "Outlook" folder in the ignore list, I have fixed it.
