### ISSUE TITLE
 Converts HTML file to MHTML?

### ISSUE THREAD

**Issue by kiquenet** [asposeemail/Aspose_Email_NET#25]

**Comment by kashifiqb** [comment]
Yes, you can use the API to achieve this as follow. For more information and assistance about any issues you face, please feel free to write to us on [Aspose.Email forum](http://www.aspose.com/community/forums/aspose.email-product-family/188/showforum.aspx).

MailMessage eml = MailMessage.Load("someHtmlFile.html", new Aspose.Email.Mail.HtmlLoadOptions());

eml.Save("outputMHTMLFile.mhtml", Aspose.Email.Mail.SaveOptions.DefaultMhtml);
