### ISSUE TITLE
how to delete calendar?

### ISSUE THREAD

**Issue by Guhaha** [asposeemail/Aspose_Email_NET#68]
i want to cancel calendar in my pro,but when i use the demo's method,an exception is thrown;
here is my code:
"""Appointment na = new Appointment(Location,StartDate,EndDate, Organizer, Attendees);
IEWSClient conn =IEWSClient GetEWSClient(mailboxUri, username,password);
conn.CancelAppointment(na);"""
The exception is:
"a recipient must be specified";

**Comment by aspose-email** [comment]
@Guhaha ,

We have tested this using the code sample from our online documentation with Exchange Server 2010 and were not able to reproduce the issue. Please try it with latest version of the API at your end and let us know if it helps solve the issue. If the issue persists, please share further details about the Exchange server you are trying with. We'll look into it for assisting you further.

**Comment by Guhaha** [comment]
@aspose-email ，
I want to cancel an appointment from Outlook,but it's not work.Here is my main code:
///////
IEWSClient conn = EWSClient.GetEWSClient("https://rb-ews.apac.bosch.com/ews/Exchange.asmx", "username", "password");
ExchangeMailboxInfo meetingroom = conn.GetMailboxInfo(mailboxaddr);
string calendar = meetingroom.CalendarUri;
Appointment[] myappointments = conn.ListAppointments(calendar);
string uniqueid = "xxxxx";
foreach (Appointment app in myappointments)
{
     if(app.uniqueid == uniqueid)
     {
        AlternateView aa = app.CancelApointment();
        MailMessage ac = new MailMessage("from","to","subject","body");
        ac.AddAlternateView(aa);
        conn.Send(ac);
     }
}
///////
Can you please give a demo that can make me cancel/delete an appointment by using uniqueid or other things?

**Comment by aspose-barcode** [comment]
@Guhaha ,

The Appointment.CancelAppointment method doesn't work with UID of Appointment, but with sequence id. Please use the IEWSClient.CancelAppointment to cancel the appointment using its UID. 

`conn.CancelAppointment(uid);`
