### ISSUE TITLE
Changes in MailMessage.Save for TNEF messages

### ISSUE THREAD

**Issue by dave0292** [asposeemail/Aspose_Email_NET#77]
Hi, 

  I have been working on a project using MimeKit and Aspose and I have seen that I'm no longer able to open a MimeMessage in MimeKit if it's saved with MailMessage class specifying "FileCompatibilityMode.PreserveTnefAttachments" in EmlSaveOptions.

  Has been any change in the code to modify this behavior? In version 21.5.0 is working correctly, but in the last one 21.10.0 after updating with nuget is not working. 

Thanks in advance, 

  David.

**Comment by andreypotapovaspose** [comment]
@dave0292,
Thank you for the message.

Please follow to [Aspose.Email forum](https://forum.aspose.com/c/email/), describe the issue there, and share the following:

- email message file
- code example reproducing the problem

Then we will do our best to resolve the issue.

**Comment by dmitrysamodurov** [comment]
Closed
